#!/usr/bin/env bash
# derive the symbol -> library attribution for the vendored GLFW archive.
#   tools/darwin-symbol-map.sh <archive>      writes TOML to stdout
#
# a two-level-namespace darwin target requires every dynamic import to name the
# library that provides it. the imports arriving from a vendored static archive
# have no mach declaration to decorate, so they are claimed with `symbols` on
# the `[link.<entry>]` naming their library (see mach doc/manifest.md).
#
# the mapping is READ OFF THE SDK, never guessed. modern macOS keeps no on-disk
# framework binaries -- they live in the dyld shared cache -- so the authority
# is the SDK's .tbd text stubs, which list exactly what each library exports.
#
# `symbols` entries are SOURCE-LEVEL names: mach applies the target's leading
# underscore itself, so the Mach-O `___assert_rtn` is written `__assert_rtn`.
# this script strips exactly one leading underscore for that reason.
set -euo pipefail

archive=${1:?usage: tools/darwin-symbol-map.sh <archive>}
sdk=$(xcrun --sdk macosx --show-sdk-path)

# candidates in precedence order: most specific first, umbrellas last. Cocoa
# re-exports AppKit/Foundation/CoreData, so it must lose to them or every class
# would be attributed to the umbrella and the real provider never named.
#   <manifest link entry>:<tbd path under the sdk>
candidates="
libSystem:usr/lib/libSystem.B.tbd
objc:usr/lib/libobjc.A.tbd
CoreFoundation:System/Library/Frameworks/CoreFoundation.framework/CoreFoundation.tbd
CoreGraphics:System/Library/Frameworks/CoreGraphics.framework/CoreGraphics.tbd
CoreServices:System/Library/Frameworks/CoreServices.framework/CoreServices.tbd
IOKit:System/Library/Frameworks/IOKit.framework/IOKit.tbd
CoreVideo:System/Library/Frameworks/CoreVideo.framework/CoreVideo.tbd
OpenGL:System/Library/Frameworks/OpenGL.framework/OpenGL.tbd
Foundation:System/Library/Frameworks/Foundation.framework/Foundation.tbd
AppKit:System/Library/Frameworks/AppKit.framework/AppKit.tbd
Cocoa:System/Library/Frameworks/Cocoa.framework/Cocoa.tbd
"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# undefined externals the archive actually imports: everything nm reports as
# undefined, minus everything the archive defines itself (intra-archive
# references between members show up as undefined per-member and resolve at
# link time -- attributing those to a system library would be wrong).
nm -u "$archive" 2>/dev/null | awk '{print $NF}' | grep '^_' | sort -u > "$work/undef.all"
nm -g --defined-only "$archive" 2>/dev/null | awk '{print $NF}' | grep '^_' | sort -u > "$work/defined"
comm -23 "$work/undef.all" "$work/defined" > "$work/undef"

echo "# generated by tools/darwin-symbol-map.sh -- do not hand-edit" >&2
echo "# archive:   $archive" >&2
echo "# sdk:       $sdk" >&2
echo "# undefined: $(wc -l < "$work/undef.all") total, $(wc -l < "$work/defined") defined here, $(wc -l < "$work/undef") to attribute" >&2

cp "$work/undef" "$work/remaining"
: > "$work/out"

for entry in $candidates; do
    name=${entry%%:*}
    tbd=$sdk/${entry#*:}
    [ -f "$tbd" ] || { echo "# MISSING stub for $name: $tbd" >&2; continue; }

    # .tbd is YAML. rather than depend on a yaml module being present, pull every
    # symbol-shaped token out of the file and intersect with what we still need --
    # a token that is not in `remaining` cannot cause a wrong attribution.
    #
    # objective-c classes are NOT listed as symbols. they sit in a separate
    # `objc-classes` array as bare class names, so the linker-visible
    # `_OBJC_CLASS_$_NSWindow` has to be reconstructed from `NSWindow`. scan only
    # inside that array -- a bare identifier taken from anywhere in the file
    # would attribute classes to whichever stub happened to mention the name.
    {
        grep -oE '_[A-Za-z0-9_$.]+' "$tbd"
        awk '
            /objc-classes/ { inobjc = 1 }
            inobjc {
                line = $0
                gsub(/objc-classes/, "", line)
                n = split(line, tok, /[^A-Za-z0-9_]+/)
                for (i = 1; i <= n; i++)
                    if (tok[i] != "") {
                        # one class entry implies both symbols. subclassing a
                        # framework class references the metaclass too, which is
                        # how GLFW pulls in NSView/NSWindow for its own views.
                        print "_OBJC_CLASS_$_" tok[i]
                        print "_OBJC_METACLASS_$_" tok[i]
                    }
                if (index($0, "]") > 0) inobjc = 0
            }
        ' "$tbd"
    } | sort -u > "$work/exports.$name"
    comm -12 "$work/remaining" "$work/exports.$name" > "$work/claim.$name"

    if [ -s "$work/claim.$name" ]; then
        printf '%s %s\n' "$name" "$(wc -l < "$work/claim.$name")" >> "$work/out"
        comm -23 "$work/remaining" "$work/claim.$name" > "$work/next"
        mv "$work/next" "$work/remaining"
    fi
done

# emit the TOML fragment, one block per library that claimed anything
while read -r name count; do
    echo "# $name provides $count of the archive's imports"
    echo "symbols_for_$name = ["
    # strip exactly one leading underscore: `symbols` is source-level and mach
    # re-applies the target's prefix itself
    sed 's/^_//' "$work/claim.$name" | awk ' {
        item = "\"" $0 "\", "
        
        if (line == "") {
            line = "    " item
        } else if (length(line) + length(item) > 72) {
            print line
            line = "    " item
        } else {
            line = line item
        }
    } END {
        if (length(line) > 0) {
            sub(/, $/, "", line)
            print line
        }
    }'
    echo "]"
    echo
done < "$work/out"

if [ -s "$work/remaining" ]; then
    echo "# UNATTRIBUTED -- no candidate library exports these:"
    sed 's/^/#   /' "$work/remaining"
    echo "# ($(wc -l < "$work/remaining") symbols)"
fi
