#!/bin/sh
# regenerate or verify src/glfw.mach, the flat public surface.
#   tools/surface.sh gen     rewrite src/glfw.mach from the split modules
#   tools/surface.sh check   exit nonzero if src/glfw.mach is out of date
set -eu
cd "$(dirname "$0")/.."

MODULES="core window monitor input key hint err mouse joystick vulkan"

generate() {
    cat <<'EOF'
# the flat public surface of the GLFW bindings
#
# GENERATED by tools/surface.sh; do not edit by hand. run
# `tools/surface.sh gen` after changing any split module's public surface.
#
# re-exports every binding under one namespace so consumers can write
# `use glfw.glfw;` and reach the whole API as glfw.init(),
# glfw.create_window(), glfw.KEY_ESCAPE, and so on. the split modules
# (glfw.core, glfw.window, ...) remain importable individually.

use glfw.c;
EOF
    for m in $MODULES; do printf 'use glfw.%s;\n' "$m"; done
    printf '\nfwd c.Vidmode;\nfwd c.Gammaramp;\nfwd c.Image;\nfwd c.Gamepadstate;\n'
    for m in $MODULES; do
        grep -oE 'pub (ext )?(val|fun|rec|def) [A-Za-z_][A-Za-z0-9_]*' "src/$m.mach" |
            awk -v m="$m" '{
                if ($2 == "ext") {
                    print m"."$4
                } else {
                    print m"."$3
                }
            }'
    done | LC_ALL=C sort | awk -F. ' {
        if (!($NF in seen)) {
            seen[$NF] = $0
            print "fwd "$0";"
        } else {
            print "# dup " $0 " (shadowed by " seen[$NF] ")" > "/dev/stderr"
        }
    } '
}

case "${1:-}" in
    gen)   generate 2>/dev/null > src/glfw.mach ;;
    check) generate | diff -u src/glfw.mach - >&2 || {
               echo "src/glfw.mach is out of date; run tools/surface.sh gen" >&2
               exit 1
           } ;;
    *)     echo "usage: tools/surface.sh gen|check" >&2; exit 2 ;;
esac
